### registration
POST localhost:8081/api/v1/auth/registration
Content-Type:  application/json

{
  "name": "Elmurod",
  "surname": "Shirinov",
  "phone": "+998914082930",
  "email": "shirinovelmurod@gmail.com",
  "password": "123456"
}

### login
POST localhost:8081/api/v1/auth
Content-Type: application/json

{
  "email": "shirinovelmurod@gmail.com",
  "password": "123456"
}