### category create
POST localhost:8081/api/v1/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1NzkyMzIsImVtYWlsIjoic2hpcmlub3ZlbG11cm9kQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNjg0NjY1NjMyLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.-rPiwUFIVYsCjMdi9YB9vkJejVrWaA2dN6Znk1qTD0mQ8T82ln_OHYPIv8mfTLTuJc29slvnEZVeEwnmj-D3Ww
Content-Type: application/json

{
  "name": "music"
}

### categegory update
PUT localhost:9090/api/v1/category/

### category delete
DELETE localhost:9090/api/v1/category/

### category List
GET localhost:9090/api/v1/category
