### Change Password
PUT localhost:8080/api/v1/profile/public/change-password
Content-Type: application/json

{
  "email": "azizbek@gmail.com",
  "oldPassword": "3333",
  "newPassword": "4444"
}

###
POST localhost:8080/api/v1/profile/private/create
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1ODQyNjksImVtYWlsIjoic290aWJvbGRpeWV2YXppemJlazg2QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE2ODQ2NzA2NjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.Gk_4o-KcPEOWgXNcKX9y0pZ1FuQz8pEnhgwURPzwGnZjr_i-JHdCfUMEsCnj_2Fgkz0ik8iYz1VVSryTrcnaLg
Content-Type: application/json

{
  "name": "Azizbek",
  "surname": "Sotiboldiyev",
  "email": "sotiboldiyevazizbek86@gamil.com",
  "password": "3333",
  "role": "ROLE_USER"
}


### Get all detail
GET localhost:8080/api/v1/profile/get-all-detail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMDYyODQsImVtYWlsIjoibW9kZXJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNjg0MzkyNjg0LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.-82uz9WtJRCdWK5RZzF9zrerzdNX7CyP9_Db2Cbu9boIqas_S5jhdXJGwj0Q8d-PkNdabQMajIpqTjisItrsTA

